version: '3.8'

services:
  frontend:
    image: models-reactjs-prod
    container_name: host-prod-frontend
    build:
      context: ./frontend
      dockerfile: ../provision/frontend/production/Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - main

  backend:
    image: models-nodejs-prod
    container_name: host-prod-backend
    build:
      context: ./backend
      dockerfile: ../provision/backend/production/Dockerfile
    ports:
      - 5001:5001
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - main

networks:
  main:
    driver: bridge